### ISSUE TITLE
Dijkastra Algorithm needed as Class

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Graph-Algorithm#1]
the class graph should be there and Dijkstra as it's a member function. 
which prints the shortest path. of the given source to destination

**Comment by solanki2899** [comment]
I want to work on this in C++ . Pls assign this to me.

**Comment by solanki2899** [comment]
I made a Pull request, pls do check it.

**Comment by pradeexsu** [comment]
@solanki2899, please create ```src``` folder and move your file into ```src```.

**Comment by solanki2899** [comment]
I made the required changes. pls review it.
