### ISSUE TITLE
Bellman-Ford Algorithm Implementation

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Graph-Algorithm#4]
implement a Graph class that contains Bellman-Ford algorithm as function.
read ![README.md](https://github.com/metoop/Graph-Algorithm/blob/main/README.md) carefully before your first pull request.
**DO NOT RAISE A PR BEFORE YOU HAVE BEEN ASSIGNED. YOUR PR WILL STAND INVALID.**

**Comment by siddhhu** [comment]
Hello @sutharp777 sir,
I want to work on this

**Comment by pradeexsu** [comment]
yes do
